### ISSUE TITLE
Connect 4 winning

### ISSUE THREAD

**Issue by uktechreviews** [Ibi-M/game_centre_final#3]
Start with row6
             Repeat 4 times
                          start with column 1 and check the first 4 spaces
                          move along 1
Then repeat with row 5 - 1

**Comment by Ibi-M** [comment]
> Start with row6 Repeat 4 times start with column 1 and check the first 4 spaces move along 1 Then repeat with row 5 - 1

I have managed to do the horizontal now.
I just need a little help on how to do the 2 diagonals

Thanks
